services:
  app:
    build: ./java-api-spring-data-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productsdb
      LOGGING_LEVEL_ROOT: INFO
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: productsdb
      POSTGRES_PASSWORD: pass1234